Repository pknu-wap/Do-Learn, pull requests merged in 2025-04, with the labels that each got.

#19 Feature : 스터디 그룹 생성 폼 틀 구현
  client/package-lock.json
  client/package.json
  client/src/features/StudyGroupForm.tsx
  client/src/pages/MainPage.tsx
Labels: 🐹시은, ☀️Frontend

#36 feature: 헤더, navigation bar UI 추가
  client/package-lock.json
  client/package.json
  client/public/assets/home-icon.png
  client/public/assets/logo.png
  client/public/assets/menu-icon.png
  client/public/assets/mypage-icon.png
  client/public/assets/search-icon.png
  client/src/features/header/Header.scss
  client/src/features/header/Header.tsx
  client/src/features/navBar/NavBar.tsx
  client/src/features/searchBar/SearchBar.tsx
  client/src/features/studyGroupList/StudyGroupsList.scss
  client/src/features/studyGroupList/StudyGroupsList.tsx
  client/src/pages/MainPage.tsx
Labels: 🐰채연, ☀️Frontend

#38 Feature : #32 nav bar 구현
  client/package-lock.json
  client/package.json
  client/src/assets/style/NavBar.scss
  client/src/assets/style/global.scss
  client/src/components/Layout.tsx
  client/src/components/NavBar.tsx
  client/src/pages/MainPage.tsx
Labels: 🐹시은, ☀️Frontend

#39 Feature/scss 추가 및 변경
  client/src/assets/style/NavBar.scss
  client/src/assets/style/_colors.scss
  client/src/assets/style/_typography.scss
  client/src/features/header/Header.scss
  client/src/features/header/Header.tsx
  client/src/features/searchBar/SearchBar.scss
  client/src/features/searchBar/SearchBar.tsx
  client/src/features/studyGroupList/StudyGroupsList.scss
Labels: 🐹시은, ☀️Frontend

#40 feature : 그룹 생성 폼 수정
  client/src/assets/style/_colors.scss
  client/src/assets/style/_typography.scss
  client/src/components/NavBar.scss
  client/src/components/NavBar.tsx
  client/src/features/studyGroupForm/StudyGroupForm.scss
  client/src/features/studyGroupForm/StudyGroupForm.tsx
Labels: 🐹시은, ☀️Frontend

#42 Feature/그룹 상세 페이지 틀
  client/src/assets/style/_color.scss
  client/src/features/searchBar/SearchBar.scss
  client/src/features/searchBar/SearchBar.tsx
Labels: 🐹시은, ☀️Frontend

#49 add domain data #30
  backend/src/main/java/com/wap/web1/domain/Category.java
  backend/src/main/java/com/wap/web1/domain/Region.java
  backend/src/main/java/com/wap/web1/domain/StudyGroup.java
Labels: 🌙Backend

#56 Feature/#54 navbar route handling
  client/src/components/NavBar.scss
  client/src/components/NavBar.tsx
  client/src/features/login/LoginForm.scss
  client/src/features/login/LoginForm.tsx
  client/src/features/login/SignupForm.scss
  client/src/features/login/SignupForm.tsx
  client/src/features/logoutButton/LogoutButton.scss
  client/src/features/logoutButton/LogoutButton.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/MyPage.tsx
Labels: 🐰채연, ☀️Frontend
