Repository pknu-wap/Do-Learn, pull requests merged in 2025-05, with the labels that each got.

#67 Feature : 그룹 리스트 스타일 변경
  client/src/features/studyGroupList/StudyGroupItem.tsx
  client/src/features/studyGroupList/StudyGroupsList.scss
Labels: 🐹시은, ☀️Frontend

#68 feature : 폼 수정
  client/src/api/createGroupFormApi.ts
  client/src/components/NavBar.scss
  client/src/features/studyGroupForm/StudyGroupForm.scss
  client/src/features/studyGroupForm/StudyGroupForm.tsx
Labels: 🐹시은, ☀️Frontend

#69 닉네임 중복 방지 (#65)
  backend/src/main/java/com/wap/web1/repository/UserRepository.java
  backend/src/main/java/com/wap/web1/service/JoinService.java
  backend/src/main/resources/application.properties
Labels: 🌙Backend

#70 feature : 그룹 생성 폼 수정
  client/src/api/createGroupFormApi.ts
  client/src/features/studyGroupForm/StudyGroupForm.scss
  client/src/features/studyGroupForm/StudyGroupForm.tsx
Labels: 🐹시은, ☀️Frontend

#75 fix : 버그 수정
  client/src/api/createGroupFormApi.ts
Labels: bug, 🐹시은

#80 DL BE - 출석 기능 구현
  backend/src/main/java/com/wap/web1/controller/StudyGroupController.java
  backend/src/main/java/com/wap/web1/domain/Attendance.java
  backend/src/main/java/com/wap/web1/domain/StudyMember.java
  backend/src/main/java/com/wap/web1/dto/AttendanceCalendarDto.java
  backend/src/main/java/com/wap/web1/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/wap/web1/repository/AttendanceRepository.java
  backend/src/main/java/com/wap/web1/repository/StudyMemberRepository.java
  backend/src/main/java/com/wap/web1/scheduler/AttendanceResetScheduler.java
  backend/src/main/java/com/wap/web1/service/StudyGroupService.java
Labels: 🪄 Feature

#89 DL FE #88 - 닉네임 중복 검사 구현
  client/src/features/login/SignupForm.tsx
Labels: 🪄 Feature

#92 DL FE #87 - 실시간 검색 결과
  client/src/features/searchBar/SearchBar.tsx
Labels: 🐞 BugFix, 🥹 help wanted

#94 DL BE - SecurityConfig수정
  backend/src/main/java/com/wap/web1/comfig/SecurityConfig.java
Labels: 🐞 BugFix

#96 DL FE #90 - 스터디 그룹 가입 모달
  client/src/api/groupNotice.ts
  client/src/features/studyGroupList/GroupInfoModal.scss
  client/src/features/studyGroupList/GroupInfoModal.tsx
  client/src/features/studyGroupList/StudyGroupItem.tsx
Labels: 🪄 Feature

#97 DL BE - 디버깅용 로그 추가
  backend/src/main/java/com/wap/web1/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/wap/web1/jwt/JWTFilter.java
  backend/src/main/java/com/wap/web1/repository/StudyMemberRepository.java
Labels: 🐞 BugFix

#99 DL BE #98 - securityConfig 수정
  backend/.idea/modules.xml
  backend/build.gradle
  backend/src/main/java/com/wap/web1/comfig/SecurityConfig.java
Labels: 🐞 BugFix

#102 DL FE #101 - 그룹 생성 폼 403 오류 해결
  client/src/features/studyGroupForm/StudyGroupForm.tsx
Labels: 🐞 BugFix

#105 DL BE #98 - application.properties 지워진거 복구
  backend/src/main/resources/application.properties
Labels: 🐞 BugFix

#106 DL BE #98 - JWTDecoder 충돌 제거
  backend/src/main/java/com/wap/web1/comfig/SecurityConfig.java
  backend/src/main/resources/application.properties
Labels: 🐞 BugFix

#108 DL FE #107 - Access Token 리이슈 처리
  client/src/App.tsx
  client/src/api/auth.ts
  client/src/features/studyGroupList/GroupInfoModal.scss
  client/src/features/studyGroupList/GroupInfoModal.tsx
  client/src/features/studyGroupList/StudyGroupItem.tsx
  client/src/features/studyGroupList/StudyGroupsList.scss
Labels: 🪄 Feature

#109 DL BE #9 - 내 그룹 리스트 현재 멤버 수 관련 수정
  backend/src/main/java/com/wap/web1/dto/GroupMemberCount.java
  backend/src/main/java/com/wap/web1/repository/StudyMemberRepository.java
  backend/src/main/java/com/wap/web1/service/UserService.java
Labels: 🪄 Feature

#111 DL FE #86 - 마이페이지 프로필 구현
  client/src/api/myInfoApi.ts
  client/src/features/header/Header.scss
  client/src/features/myPage/JoinGroupList.scss
  client/src/features/myPage/JoinGroupList.tsx
  client/src/features/myPage/LogoutButton.scss
  client/src/features/myPage/LogoutButton.tsx
  client/src/features/myPage/Profile.scss
  client/src/features/myPage/Profile.tsx
  client/src/pages/MyPage.tsx
Labels: 🪄 Feature

#112 DL BE - 유효성 검사 추가 등 코드수정
  backend/src/main/java/com/wap/web1/comfig/SecurityConfig.java
  backend/src/main/java/com/wap/web1/domain/User.java
  backend/src/main/java/com/wap/web1/dto/GroupMembersDto.java
  backend/src/main/java/com/wap/web1/dto/MyInfoDto.java
  backend/src/main/java/com/wap/web1/dto/MyInfoUpdateDto.java
  backend/src/main/java/com/wap/web1/scheduler/StudyScheduler.java
  backend/src/main/java/com/wap/web1/service/JoinService.java
  backend/src/main/java/com/wap/web1/service/StudyGroupService.java
  backend/src/main/java/com/wap/web1/service/UserService.java
Labels: 🪄 Feature

#116 DL FE #18 - 그룹 생성 폼
  client/src/components/NavBar.tsx
  client/src/features/studyGroupForm/StudyGroupForm.scss
  client/src/features/studyGroupForm/StudyGroupForm.tsx
Labels: 🪄 Feature

#117 DL BE #9 - 내 그룹 리스트 isLeader필드추가
  backend/src/main/java/com/wap/web1/dto/MyStudyGroupDto.java
  backend/src/main/java/com/wap/web1/service/UserService.java
Labels: 🪄 Feature

#118 DL FE #84 - Filter 기능 구현
  client/src/api/searchFilterApi.ts
  client/src/features/filter/filter.scss
  client/src/features/filter/filter.tsx
  client/src/features/searchBar/SearchBar.scss
  client/src/pages/MainPage.tsx
Labels: 🪄 Feature

#119 DL FE #84 - 스타일 수정
  client/src/features/filter/filter.scss
  client/src/features/filter/filter.tsx
  client/src/pages/MainPage.tsx
Labels: 🪄 Feature, 🎨 Style

#120 DL FE #84 - 첫 페이지에 대해서만 필터링 되는 오류 수정
  client/src/pages/MainPage.tsx
Labels: 🐞 BugFix

#122 DL FE - 그룹 상세 페이지 ui 수정
  client/src/features/groupDetail/GroupMemberList.tsx
  client/src/features/groupDetail/GroupMenu.scss
  client/src/features/groupDetail/GroupMenu.tsx
  client/src/features/myPage/JoinGroupList.scss
  client/src/features/myPage/JoinGroupList.tsx
Labels: 🎨 Style

#124 DL FE - 그룹 상세 페이지 메뉴 눌렀을 때 해당 tab 뜨도록
  client/src/api/myInfoApi.ts
  client/src/features/groupDetail/GroupMenu.scss
  client/src/features/groupDetail/GroupMenu.tsx
  client/src/features/groupDetail/tabs/AttendanceTab.scss
  client/src/features/groupDetail/tabs/AttendanceTab.tsx
  client/src/features/groupDetail/tabs/GoalTab.scss
  client/src/features/groupDetail/tabs/GoalTab.tsx
  client/src/features/groupDetail/tabs/GroupInfoTab.scss
  client/src/features/groupDetail/tabs/GroupInfoTab.tsx
  client/src/features/groupDetail/tabs/RankingTab.scss
  client/src/features/groupDetail/tabs/RankingTab.tsx
  client/src/features/myPage/Profile.scss
  client/src/features/myPage/Profile.tsx
  client/src/pages/GroupPage.tsx
Labels: 🪄 Feature

#127 DL FE #86 - 닉네임 중복 오류 처리 변경
  client/src/features/myPage/Profile.tsx
Labels: 🪄 Feature

#131 DL FE #128 - 오늘 날짜로 돌아가기 추가 구현
  client/src/features/groupDetail/tabs/AttendanceTab.scss
  client/src/features/groupDetail/tabs/AttendanceTab.tsx
Labels: 🪄 Feature

#137 DL BE - 스터디 삭제 구현
  backend/src/main/java/com/wap/web1/controller/UserController.java
  backend/src/main/java/com/wap/web1/repository/AttendanceRepository.java
  backend/src/main/java/com/wap/web1/repository/StudyMemberRepository.java
  backend/src/main/java/com/wap/web1/repository/StudyRankingRepository.java
  backend/src/main/java/com/wap/web1/service/StudyGroupService.java
  backend/src/main/java/com/wap/web1/service/UserService.java
Labels: 🪄 Feature

#144 DL BE - 공통목표 및 개인위클리 구현
  backend/build.gradle
  backend/src/main/java/com/wap/web1/StudyManagementApplication.java
  backend/src/main/java/com/wap/web1/config/CurrentUser.java
  backend/src/main/java/com/wap/web1/config/CustomUserDetailsService.java
  backend/src/main/java/com/wap/web1/config/QuerydslConfig.java
  backend/src/main/java/com/wap/web1/config/SecurityConfig.java
  backend/src/main/java/com/wap/web1/controller/MainController.java
  backend/src/main/java/com/wap/web1/controller/StudyGroupController.java
  backend/src/main/java/com/wap/web1/controller/UserController.java
  backend/src/main/java/com/wap/web1/controller/WeeklyGoalController.java
  backend/src/main/java/com/wap/web1/controller/WeeklyPlanController.java
  backend/src/main/java/com/wap/web1/controller/WeeklySubGoalController.java
  backend/src/main/java/com/wap/web1/domain/MemberWeeklyPlan.java
  backend/src/main/java/com/wap/web1/domain/PersonalTask.java
  backend/src/main/java/com/wap/web1/domain/StudyGroup.java
  backend/src/main/java/com/wap/web1/domain/StudyMember.java
  backend/src/main/java/com/wap/web1/domain/StudyRanking.java
  backend/src/main/java/com/wap/web1/domain/WeeklyGoal.java
  backend/src/main/java/com/wap/web1/domain/WeeklyPeriod.java
  backend/src/main/java/com/wap/web1/domain/WeeklySubGoal.java
  backend/src/main/java/com/wap/web1/dto/MemberRankingDto.java
  backend/src/main/java/com/wap/web1/dto/StudyRankDto.java
  backend/src/main/java/com/wap/web1/dto/WeeklyGoalCompletionResponse.java
  backend/src/main/java/com/wap/web1/dto/WeeklyGoalDto.java
  backend/src/main/java/com/wap/web1/dto/WeeklyPlanRequest.java
  backend/src/main/java/com/wap/web1/dto/WeeklyPlanResponse.java
  backend/src/main/java/com/wap/web1/dto/WeeklyProgressDto.java
  backend/src/main/java/com/wap/web1/dto/WeeklySubGoalDto.java
  backend/src/main/java/com/wap/web1/mapper/StudyGroupMapper.java
  backend/src/main/java/com/wap/web1/mapper/WeeklyGoalMapper.java
  backend/src/main/java/com/wap/web1/repository/MemberWeeklyPlanRepository.java
  backend/src/main/java/com/wap/web1/repository/MemberWeeklyPlanRepositoryCustom.java
  backend/src/main/java/com/wap/web1/repository/MemberWeeklyPlanRepositoryImpl.java
  backend/src/main/java/com/wap/web1/repository/PersonalTaskRepository.java
  backend/src/main/java/com/wap/web1/repository/StudyMemberRepository.java
  backend/src/main/java/com/wap/web1/repository/WeeklyGoalRepository.java
  backend/src/main/java/com/wap/web1/repository/WeeklyPeriodRepository.java
  backend/src/main/java/com/wap/web1/repository/WeeklySubGoalRepository.java
  backend/src/main/java/com/wap/web1/scheduler/ResetScheduler.java
  backend/src/main/java/com/wap/web1/service/MemberWeeklyPlanService.java
  backend/src/main/java/com/wap/web1/service/PersonalTaskService.java
  backend/src/main/java/com/wap/web1/service/StudyGroupFilterSearchService.java
  backend/src/main/java/com/wap/web1/service/StudyGroupListService.java
  backend/src/main/java/com/wap/web1/service/WeeklyGoalService.java
  backend/src/main/java/com/wap/web1/service/WeeklyPlanService.java
  backend/src/main/java/com/wap/web1/service/WeeklySubGoalService.java
  backend/src/main/java/com/wap/web1/util/WeeklyPeriodCalculator.java
Labels: 🪄 Feature

#145 DL BE - 진행도 구현
  backend/src/main/java/com/wap/web1/controller/ProgressController.java
  backend/src/main/java/com/wap/web1/scheduler/ResetScheduler.java
  backend/src/main/java/com/wap/web1/service/MemberWeeklyPlanService.java
  backend/src/main/java/com/wap/web1/service/ProgressService.java
  backend/src/main/resources/application.properties
Labels: 🪄 Feature

#146 DL BE - 랭킹 구현
  backend/src/main/java/com/wap/web1/controller/RankingController.java
  backend/src/main/java/com/wap/web1/repository/StudyRankingRepository.java
  backend/src/main/java/com/wap/web1/repository/StudyRankingRepositoryCustom.java
  backend/src/main/java/com/wap/web1/repository/StudyRankingRepositoryImpl.java
  backend/src/main/java/com/wap/web1/scheduler/RankingScheduler.java
  backend/src/main/java/com/wap/web1/service/RankingService.java
Labels: 🪄 Feature

#148 DL BE #125 - 내 그룹 수정 및 연동
  client/package-lock.json
  client/package.json
  client/src/api/editMyGroupApi.ts
  client/src/api/kickMemberApi.ts
  client/src/api/studyGroupApi.ts
  client/src/api/updateLeaderApi.ts
  client/src/features/editGroups/EditGroupModal.scss
  client/src/features/editGroups/EditGroupModal.tsx
  client/src/features/myGroupsList/MyGroupsList.scss
  client/src/features/myGroupsList/MyGroupsList.tsx
  client/src/features/studyGroupForm/StudyGroupForm.scss
  client/src/features/studyGroupForm/StudyGroupForm.tsx
  client/src/features/studyGroupList/StudyGroupItem.tsx
  client/src/features/studyGroupList/StudyGroupsList.scss
  client/src/hooks/useMyStudyGroups.ts
  client/src/utils/StudyGroup.ts
Labels: 🪄 Feature

#153 DL FE #130 - 랭킹 구현
  client/src/api/memberListApi.ts
  client/src/api/rankingApi.ts
  client/src/assets/icon/crown.png
  client/src/features/groupDetail/GroupMemberList.tsx
  client/src/features/groupDetail/tabs/RankingTab.scss
  client/src/features/groupDetail/tabs/RankingTab.tsx
  client/src/features/myPage/Profile.tsx
  client/src/utils/profileImageMap.ts
Labels: 🪄 Feature
