Repository pknu-wap/Do-Learn, pull requests merged in 2025-06, with the labels that each got.

#158 Feature/#154 group delete
  client/src/api/studyGroupApi.ts
  client/src/features/editGroups/EditGroupModal.scss
  client/src/features/editGroups/EditGroupModal.tsx
  client/src/features/groupDetail/tabs/RankingTab.scss
  client/src/features/groupDetail/tabs/RankingTab.tsx
Labels: 🪄 Feature

#165 DL FE #162 - 1~3등 사이에 있는 유저가 아래 리스트에도 뜨는 오류 수정
  client/src/features/groupDetail/tabs/RankingTab.tsx
Labels: 🐞 BugFix

#166 DL FE #161 - 임시 개인 목표 설정
  client/src/api/personalGoalsApi.ts
  client/src/features/groupDetail/tabs/goalTab/CommonGoals.tsx
  client/src/features/groupDetail/tabs/goalTab/PersonalGoals.scss
  client/src/features/groupDetail/tabs/goalTab/PersonalGoals.tsx
  client/src/features/groupDetail/tabs/goalTab/WeeklyGoalModal.scss
  client/src/features/groupDetail/tabs/goalTab/WeeklyGoalModal.tsx
  client/src/types/personalGoalTypes.ts
Labels: 🪄 Feature

#168 DL BE - 스터디 삭제 시 의존성 문제 해결
  backend/.idea/compiler.xml
  backend/Rebuild
  backend/build.gradle
  backend/src/main/java/com/wap/web1/repository/MemberWeeklyPlanRepository.java
  backend/src/main/java/com/wap/web1/repository/PersonalTaskRepository.java
  backend/src/main/java/com/wap/web1/repository/StudyRankingRepository.java
  backend/src/main/java/com/wap/web1/repository/WeeklyGoalRepository.java
  backend/src/main/java/com/wap/web1/repository/WeeklyPeriodRepository.java
  backend/src/main/java/com/wap/web1/repository/WeeklySubGoalRepository.java
  backend/src/main/java/com/wap/web1/service/UserService.java
  backend/src/main/resources/application.properties
Labels: 🐞 BugFix

#169 DL FE - UI 수정
  client/public/assets/img/ranking/profile-2nd.jpg
  client/public/assets/img/ranking/profile-3rd.jpg
  client/public/assets/logo.png
  client/public/assets/profile_images/profile-1st.png
  client/public/assets/profile_images/profile-2nd.png
  client/public/assets/profile_images/profile-3rd.png
  client/public/assets/profile_images/profile-default.png
  client/public/favicon.ico
  client/src/assets/style/_colors.scss
  client/src/assets/style/global.scss
  client/src/features/filter/filter.scss
  client/src/features/groupDetail/GroupMenu.scss
  client/src/features/groupDetail/tabs/GoalTab.scss
  client/src/features/groupDetail/tabs/GoalTab.tsx
  client/src/features/groupDetail/tabs/GroupInfoTab.scss
  client/src/features/groupDetail/tabs/GroupInfoTab.tsx
  client/src/features/header/Header.scss
  client/src/features/header/Header.tsx
  client/src/features/myGroupsList/MyGroupsList.tsx
  client/src/features/myPage/Profile.scss
  client/src/features/searchBar/SearchBar.scss
  client/src/features/studyGroupForm/StudyGroupForm.scss
  client/src/features/studyGroupList/GroupInfoModal.scss
  client/src/features/studyGroupList/StudyGroupsList.scss
  client/src/pages/MainPage.tsx
Labels: 🎨 Style

#172 DL FE - 비로그인시 처리 변경
  client/public/assets/img/ranking/profile-3rd-2.jpg
  client/public/assets/img/ranking/profile-3rd.jpg
  client/src/api/rankingApi.ts
  client/src/features/editGroups/EditGroupModal.tsx
  client/src/features/groupDetail/tabs/GroupInfoTab.scss
  client/src/features/groupDetail/tabs/GroupInfoTab.tsx
  client/src/features/groupDetail/tabs/RankingTab.tsx
  client/src/features/myPage/Profile.tsx
  client/src/features/studyGroupForm/StudyGroupForm.tsx
  client/src/pages/StartPage.scss
Labels: 🪄 Feature

#177 DL BE - 멤버리스트 프로필사진 수정
  backend/.gitignore
  backend/src/main/java/com/wap/web1/service/StudyGroupService.java
Labels: 🐞 BugFix

#178 DL FE - 목표 임시 수정
  client/src/api/commonGoalsApi.ts
  client/src/api/personalGoalsApi.ts
  client/src/features/groupDetail/tabs/goalTab/PersonalGoals.tsx
  client/src/features/groupDetail/tabs/goalTab/WeeklyGoalModal.tsx
Labels: 🐞 BugFix

#179 배포
  backend/.gitignore
  backend/src/main/java/com/wap/web1/service/StudyGroupService.java
  client/src/api/commonGoalsApi.ts
  client/src/api/personalGoalsApi.ts
  client/src/features/groupDetail/tabs/goalTab/PersonalGoals.tsx
  client/src/features/groupDetail/tabs/goalTab/WeeklyGoalModal.tsx
Labels: 💡 Deploy
